# fly.toml file generated for aged-water-4325 on 2023-04-10T21:57:57+02:00

app = "aged-water-4325"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "mad"
processes = []

[env]
  PORT = "8080" # add this

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
